mdapipkg/unpackaged/objects/sa_details__c.object
<CustomObject>
    <fields>
        <fullName>Experience__c</fullName>
        <label>Experience</label>
        <precision>18</precision>
        <scale>0</scale>
        <type>Number</type>
    </fields>
    <fields>
        <fullName>Name__c</fullName>
        <label>Name</label>
        <length>255</length>
        <type>Text</type>
    </fields>
    <fields>
        <fullName>Supervisor__c</fullName>
        <label>Supervisor</label>
        <referenceTo>Contact</referenceTo>
        <relationshipLabel>sa details</relationshipLabel>
        <relationshipName>sa_details</relationshipName>
        <relationshipOrder>0</relationshipOrder>
        <type>MasterDetail</type>
    </fields>
    <label>sa details</label>
    <nameField>
        <displayFormat>SA- {00000}</displayFormat>
        <label>sa details</label>
        <type>AutoNumber</type>
    </nameField>
    <pluralLabel>sa details</pluralLabel>
    <sharingModel>ControlledByParent</sharingModel>
</CustomObject>

force-app/main/default/classes/SAManagerTest.cls
@isTest
public class SAManagerTest {
	@isTest
    static void testMethods (){
       Contact supervisor = new Contact(lastname='testSUpervisor'); 
       insert supervisor;
       SA_details__c sa = new SA_details__c (Experience__c = 3, Name__c='TestSA', Supervisor__c = supervisor.Id);
       insert sa;
       List<SA_details__c> saList = SAManager.getAllSA();
       System.assert(saList.size()>0);

       List<SA_details__c> saList2 = SAManager.searchSas('Test');
       System.assert(saList2.size()>0);
               
    }
}